### ISSUE TITLE
In certain cases, Shift-Tab leaves the cursor incorrectly placed on the previous line.

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#1105]
This minor annoyance has bothered me for at least several months, perhaps for a year or more.

## The Certain Cases

I'm only fairly sure, not certain, that this description of the problem is correct.  But even if it is slightly wrong, it should allow you to easily reproduce the problem and correct this description as necessary.

Suppose Shift-Tab moves the left margin K columns to the left.  The bug is that Shift-Tab always moves the cursor K columns to the left.  Hence, if the cursor is at column N and N < K, then Shift-Tab moves the cursor into the previous line.

## Fix

Shift-Tab should always move the cursor min(K, N) columns to the left.

## Test System
```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190227233831, Wed Feb 27 23:38:31 PST 2019
Git repo info: branch = devel, commit = 9e42b2e5d620
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
```

**Comment by vitalije** [comment]
Fixed at  39653ec.
The solution was not just that simply like you have suggested `min(N, K)`. Leo now recalculates insert point relative to the end of line containing insert point. Meaning of this relative position is not changed by unindenting the line.

**Comment by SegundoBob** [comment]
Thanks for the effort, but the problem seems to still exist.

This is what I see from git log:
```
commit baca3d32752c9a8b9be57961cc977a33d0f9df47 (HEAD -> devel, upstream/devel, origin/devel, origin/HEAD)
Merge: 2ed16481f 23bd43de1
Author: vitalije <vitalije@kviziracija.net>
Date:   Sun Apr 7 17:00:35 2019 +0200

    Merge branch 'devel' of github.com:leo-editor/leo-editor into devel
    
    Leo build: 20190406171647

commit 2ed16481fa5c2797ba64f39767467b27639b15d7
Author: vitalije <vitalije@kviziracija.net>
Date:   Sun Apr 7 16:49:54 2019 +0200

    Fixed issue 1105
    
    changed calculation of insert point in c.dedentBody
    
    Leo build: 20190407144954
```
## By the way

[39653ec](https://github.com/leo-editor/leo-editor/commit/39653eca0dd0808d38e80b7e8a06990e965661d1)
is "best practice to upload both sdist and wheels" by maphew.  It is not your fix.

**Comment by vitalije** [comment]
Sorry, my mistake. It is the baca3d3  that you should try. The 39653ec is the latest commit in the main branch, and the fix is in the development branch.

**Comment by vitalije** [comment]
Now I see that you have tried baca3d3 and problem still exists. Strange because this version works for me. Can you elaborate what exactly behavior do you see? Also check if your Shift-Tab is bound to `unindent-region` command.

**Comment by SegundoBob** [comment]
From the output of show-bindings:
```
   all: Shift+Tab       unindent-region
```
Create an empty node.  In the first line of the body type: "This is the first line."  In the second line of the body type: "<Tab><Tab>This is indented."  Place the cursor in the second column of the second line (<Home><right-arrow><right-arrow>).  Note:  There is **NO Selected Text**.  <Shift+Tab>.  For me, this leaves the cursor between the "e" and the period on the first line.

**Comment by technatica** [comment]
I can see that here except it places the cursor between the "e" and the
"n", not the "."

Chris
Leo 5.8.1-b2 devel, build 20190227233831, Wed Feb 27 23:38:31 PST 2019
Git repo info: branch = devel, commit = 9e42b2e5d620
Python 3.6.7, PyQt version 5.12.0
linux
isPython3: True

**Comment by technatica** [comment]
Just realized I hadn't pulled the latest devel.
Git repo info: branch = devel, commit = baca3d32752c

I see the same behaviour.

Chris


Git repo info: branch = devel, commit = baca3d32752c

Git repo info: branch = devel, commit = baca3d32752c

**Comment by vitalije** [comment]
What is the output of the following script:

```
@tabwidth -13
g.es('tabwidth', c.config.getInt('tabwidth'))
g.es('local tabwidth', c.getTabWidth(c.p))
```
I have just tested that freshly cloned devel branch works as expected using your test case. Can you test this too? Here is how I obtain fresh Leo devel version with all settings set to default:

```
cd /tmp
git clone -b devel --depth 1 https://github.com/leo-editor/leo-editor.git leo-devel
cd leo-devel
python launchLeo.py /tmp/test.leo
```

And add to the test node line `@tabwidth` directive with different positive and negative integer values.
If this test works (as it does for me), then the problem is probably with some plugin you might have enabled or some other settings in effect. Here is the Leo log on my computer.

```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190406171647, Sat Apr  6 17:16:47 PDT 2019
Git repo info: branch = devel, commit = baca3d32752c
Python 3.7.0, PyQt version 5.9.6
linux
isPython3: True
setting leoID from os.getenv('USER'): 'vitalije'
current dir: /tmp/leo-devel
load dir: /tmp/leo-devel/leo/core
global config dir: /tmp/leo-devel/leo/config
home dir: /home/vitalije
reading settings in /tmp/leo-devel/leo/config/leoSettings.leo
reading settings in /tmp/proba.leo
```

**Comment by SegundoBob** [comment]
> What is the output of the following script:
```
@tabwidth -13
g.es('tabwidth', c.config.getInt('tabwidth'))
g.es('local tabwidth', c.getTabWidth(c.p))
```
Output:
```
tabwidth -4
local tabwidth -13
```
Following your instructions this is my terminal:
```
bash: enable: cannot open shared object /usr/lib/recutils/bash-builtins/readrec.so: /usr/lib/recutils/bash-builtins/readrec.so: undefined symbol: sh_xfree
2019-04-08 10:18:03 /pri/bob/1/Leo
$ cd /sec/tmp
2019-04-08 10:18:08 /sec/tmp
$ git clone -b devel --depth 1 https://github.com/leo-editor/leo-editor.git leo-devel
Cloning into 'leo-devel'...
remote: Enumerating objects: 3559, done.
remote: Counting objects: 100% (3559/3559), done.
remote: Compressing objects: 100% (3142/3142), done.
remote: Total 3559 (delta 444), reused 2666 (delta 346), pack-reused 0
Receiving objects: 100% (3559/3559), 9.33 MiB | 6.77 MiB/s, done.
Resolving deltas: 100% (444/444), done.
2019-04-08 10:18:38 /sec/tmp
$ cd leo-devel
2019-04-08 10:18:55 /sec/tmp/leo-devel
$ python launchLeo.py /tmp/test.leo

import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
Leo 5.8.1-b2 devel, build 20190406171647, Sat Apr  6 17:16:47 PDT 2019
Traceback (most recent call last):

  File "/sec/tmp/leo-devel/leo/core/leoPlugins.py", line 324, in callTagHandler
    result = handler(tag, keywords)

  File "/sec/tmp/leo-devel/leo/plugins/leo_babel/babel.py", line 49, in onCreate
    raise babel_api.BABEL_ERROR('Leo-Babel requires Python 3')

BABEL_ERROR: Leo-Babel requires Python 3
```
This is my log pane:
```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190406171647, Sat Apr  6 17:16:47 PDT 2019
Git repo info: branch = devel, commit = baca3d32752c
Python 2.7.15, PyQt version 5.9.5
linux2
isPython3: False
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
current dir: /sec/tmp/leo-devel
load dir: /sec/tmp/leo-devel/leo/core
global config dir: /sec/tmp/leo-devel/leo/config
home dir: /home/bob
reading settings in /sec/tmp/leo-devel/leo/config/leoSettings.leo
reading settings in /home/bob/.leo/myLeoSettings.leo
hook failed: after-create-leo-frame, <function onCreate at 0x7fc42b21d5f0>, leo.plugins.leo_babel.babel
Traceback (most recent call last):

   File "/sec/tmp/leo-devel/leo/core/leoPlugins.py", line 324, in callTagHandler
    result = handler(tag, keywords)

   File "/sec/tmp/leo-devel/leo/plugins/leo_babel/babel.py", line 49, in onCreate
    raise babel_api.BABEL_ERROR('Leo-Babel requires Python 3')

BABEL_ERROR: Leo-Babel requires Python 3
```

## Note
You are using Python 3.7.0.  I am using Python 2.7.15.

You are using PyQt 5.9.6.  I am using PyQt 5.9.5.

I still have many plugins enabled.  I will disable plugins after running some tests.

## Tests

My test still leaves the cursor between the "e" and the period in the first line.

When I put a @tabwidth 4 in the test node.  I get TAB characters inserted instead of spaces.  When i put the cursor at the beginning in the indented line and then hit Shift+Tab, the cursor is left at the end of the preceding line.  This is bad.

When I put @tabwidth -4 in the test node.  TAB inserts spaces and my test leaves the cursor between the "e" and the period in the preceding line.

## Disabling Plugins
My termninal:
```
2019-04-08 10:37:54 /sec/tmp/leo-devel
$ python launchLeo.py --no-plugins /tmp/test.leo

import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
Leo 5.8.1-b2 devel, build 20190406171647, Sat Apr  6 17:16:47 PDT 2019

```
My log pane:
```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190406171647, Sat Apr  6 17:16:47 PDT 2019
Git repo info: branch = devel, commit = baca3d32752c
Python 2.7.15, PyQt version 5.9.5
linux2
isPython3: False
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
current dir: /sec/tmp/leo-devel
load dir: /sec/tmp/leo-devel/leo/core
global config dir: /sec/tmp/leo-devel/leo/config
home dir: /home/bob
reading settings in /sec/tmp/leo-devel/leo/config/leoSettings.leo
reading settings in /home/bob/.leo/myLeoSettings.leo
reading settings in /tmp/test.leo
reading settings in /tmp/test.leo
may be open in another Leo:
/tmp/test.leo
read outline in 0.02 seconds
```
## Tests

My test results are all the same as before:

My test still leaves the cursor between the "e" and the period in the first line.

When I put a @tabwidth 4 in the test node.  I get TAB characters inserted instead of spaces.  When i put the cursor at the beginning in the indented line and then hit Shift+Tab, the cursor is left at the end of the preceding line.  This is bad.

When I put @tabwidth -4 in the test node.  TAB inserts spaces and my test leaves the cursor between the "e" and the period in the preceding line.

**Comment by vitalije** [comment]
I've just tested devel branch starting it with the Python2.7 and it works for me. You can change `HOME` environment variable to something other than `/home/bob`. For example:

```
cd /sec/tmp/leo-devel
export HOME=/sec/tmp
python3 launchLeo.py /sec/tmp/test.leo
```
This should make Leo believe that your home is `/sec/tmp`, therefore it won't load `/home/bob/.leo/myLeoSettings.leo` as it did before. As I can see from the logs you have posted your Leo still loads babel plugin which I don't have. I assume it is your own plugin. Do you have any `leo` folder/module installed on your `sys.path`? 

### let's test it with the <i>brute force</i>

Make a script node in any Leo outline with the headline `shift-tab @key=Alt-4` and the following body:

```
undoType = 'Unindent'
w = c.frame.body.wrapper
sel_1, sel_2 = w.getSelectionRange()
ins = w.getInsertPoint()
tab_width = c.getTabWidth(c.p)
head, lines, tail, oldSel, oldYview = c.getBodyLines()
changed, result = False, []
for line in lines:
    i, width = g.skip_leading_ws_with_indent(line, 0, tab_width)
    s = g.computeLeadingWhitespace(width - abs(tab_width), tab_width) + line[i:]
    if s != line: changed = True
    result.append(s)
if changed:
    # Leo 5.6: preserve insert point.
    preserveSel = sel_1 == sel_2
    if preserveSel:
        ins = len(result[0]) - len(lines[0]) + ins
        oldSel = ins, ins
    result = ''.join(result)
    c.updateBodyPane(head, result, tail, undoType, oldSel, oldYview, preserveSel)
```
With this node selected, execute `script-button` command. This will bind `Alt-4` to the command that should properly `unindent-region`. Now, try all your tests but pressing `Alt-4` instead of `Shift-Tab`. 
If it works then you can be sure that your Leo installation have some problems. 

One way you can overcome this installation problem would be to put in your `@settings` (in myLeoSettings.leo) the above node with the headline `@command unindent-region-2` and add `@shortcuts` node with the line:

```
unindent-region-2    =  Shift-tab
```
This will create new command `unindent-region-2` and bind it to `Shift-tab` and it will be executed instead of the broken `unindent-region` command in your installation. 
However if you find that you really have installation problem it would be better to solve it properly.

**Comment by vitalije** [comment]
If the above script doesn't work, then you may insert a few g.es(...) lines in it to dump calculated values to Log. Then we can compare values calculated and find where the difference is. Perhaps it is not `c.dedentBody` that is broken but some of it's helpers.

**Comment by SegundoBob** [comment]
## I have already tested with all plugins disabled.

As my last post states, for my last test I disabled all plugins.  This did not change the problem.

## Leo-Babel is available to you

I wrote Leo-Babel.  It has been in the master Leo-Editor repository since [Leo-Babel Pull Request](https://github.com/leo-editor/leo-editor/pull/887).

## Here are the results of your first suggestion in your next to last comment:

### Terminal:
```
2019-04-08 14:25:19 /pri/bob/1/Leo
$ cd /sec/tmp/leo-devel
2019-04-08 14:25:23 /sec/tmp/leo-devel
$ export HOME=/sec/tmp
2019-04-08 14:25:23 ~/leo-devel
$ python3 launchLeo.py /sec/tmp/test.leo

created directory: /sec/tmp/.leo
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
Leo 5.8.1-b2 devel, build 20190406171647, Sat Apr  6 17:16:47 PDT 2019
livecode.py: can not import meta
pip install meta
created: /sec/tmp/.leo/spellpyx.txt
livecode.py: can not import meta
pip install meta
```
### Log pane contents
```
Leo Log Window
Leo 5.8.1-b2 devel, build 20190406171647, Sat Apr  6 17:16:47 PDT 2019
Git repo info: branch = devel, commit = baca3d32752c
Python 3.6.7, PyQt version 5.11.1
linux
isPython3: True
created directory: /sec/tmp/.leo
import-jupyter-notebook requires nbformat package
setting leoID from os.getenv('USER'): 'bob'
current dir: /sec/tmp/leo-devel
load dir: /sec/tmp/leo-devel/leo/core
global config dir: /sec/tmp/leo-devel/leo/config
home dir: /sec/tmp
reading settings in /sec/tmp/leo-devel/leo/config/leoSettings.leo
livecode.py: can not import meta
pip install meta
created: /sec/tmp/.leo/spellpyx.txt
livecode.py: can not import meta
pip install meta
```
### Results
My test leaves the cursor between the "e" and the period in the first line.  That is, the bug occurs.

## Alt-4 (unindent-region-2)

I followed your instructions.

### Results

My test leaves the cursor between the "e" and the period in the first line.

That is, for me your code has the bug.  I tried Alt-4, and hitting the "shift-tab" script button.  I tried exiting and re-entering Leo-Editor and running the tests again.  For me in all these tests, your code has the bug.

## Instrumenting your code and running a test

The test left the cursor between the "e" and the period in the first line.  That is, the following output is produced when the bug occurs.  I believe, but I'm not certain that "ins" should **NOT** be 22 and "oldSel" should not be (22, 22).

### Instrumented Code
```
@language python

undoType = 'Unindent'
w = c.frame.body.wrapper
sel_1, sel_2 = w.getSelectionRange()
g.es('sel_1, sel_2 = {0}, {1}'.format(sel_1, sel_2), color='green')
ins = w.getInsertPoint()
tab_width = c.getTabWidth(c.p)
g.es('tab_width={0}'.format(tab_width), color='green')
head, lines, tail, oldSel, oldYview = c.getBodyLines()
g.es('head, lines, tail, oldSel, oldYview="{0}", {1}, "{2}", {3}, {4}'.format(head, lines, tail, oldSel, oldYview), color='green')
changed, result = False, []
for line in lines:
    i, width = g.skip_leading_ws_with_indent(line, 0, tab_width)
    g.es('i, width={0}, (1)'.format(i, width), color='green')
    s = g.computeLeadingWhitespace(width - abs(tab_width), tab_width) + line[i:]
    g.es('s="{0}"'.format(s), color='green')
    if s != line: changed = True
    result.append(s)
if changed:
    # Leo 5.6: preserve insert point.
    preserveSel = sel_1 == sel_2
    if preserveSel:
        ins = len(result[0]) - len(lines[0]) + ins
        g.es('ins={0}'.format(ins), color='green')
        oldSel = ins, ins
    result = ''.join(result)
    g.es('head, result, tail, undoType, oldSel, oldYview, preserveSel="{0}", "{1}", "{2}", {3}, {4}, {5}, {6}'.format(head, result, tail, undoType, oldSel, oldYview, preserveSel), color='green')
    c.updateBodyPane(head, result, tail, undoType, oldSel, oldYview, preserveSel)
```
### Instrumentation Ouput
```
sel_1, sel_2 = 26, 26
tab_width=-4
head, lines, tail, oldSel, oldYview="This is the first line.
", ['        This is indented.'], "", (24, 48), 0
i, width=8, (1)
s="    This is indented."
ins=22
head, result, tail, undoType, oldSel, oldYview, preserveSel="This is the first line.
", "    This is indented.", "", Unindent, (22, 22), 0, True
```
### Beginning Test node contents
```
This is the first line.
        This is indented.
```
### Ending Test node contents
```
This is the first line.
    This is indented.
```

**Comment by vitalije** [comment]
9bb5c2c15 should contain the proper fix. 

I am very sorry for being so blind and requiring so much testing from you. Now that I reread your initial complain it seems obvious, but I just didn't understand how to reproduce the issue. When I tried to reproduce it for the first time before fixing it, I have tested that when cursor is inside text of the second line, and `@tabwidth` is set to some larger value, after pressing `Shift-tab` cursor was moved to the previous line. With my changes in baca3d327, cursor always stayed between any two letters it was before pressing `Shift-tab`. Finally with the help of your **Instrumentation Output**, I have realized that you placed cursor in the leading white space, so I finally did reproduce bug.

Anyway, thank you for your willingness to perform all those tests. We finally nailed it.

**Comment by edreamleo** [comment]
On Tue, Apr 9, 2019 at 1:32 AM Виталије Милошевић <notifications@github.com>
wrote:

> 9bb5c2c
> <https://github.com/leo-editor/leo-editor/commit/9bb5c2c156a2197e8ac9cde64c8663334d635492>
> should contain the proper fix.
>
Many thanks, Vitalije, for this work.

Edward

**Comment by edreamleo** [comment]
Thanks to Bob and Vitalije for their work on this issue.
