### ISSUE TITLE
Undo headline typing does not select the correct node

### ISSUE THREAD

**Issue by btheado** [leo-editor/leo-editor#1333]
Steps:

1. edit a headline
2. move the selection to a different headline
3. undo

In step 3 I expect the typing to be undone. This happens as expected. However, the currently selected headline goes into edit mode rather than the headline which just had the typing undone.

Here is a failing test to illustrate. Paste as a node into leo and execute the script with ctrl-b.

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<vnodes>
<v t="bpt.20190916110038.1"><vh>@test undo editHeadline</vh>
<v t="bpt.20190916110108.1"><vh>node 1</vh></v>
<v t="bpt.20190916110117.1"><vh>node 2</vh></v>
<v t="bpt.20190916110143.1"><vh>node 3</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="bpt.20190916110038.1">c.undoer.clearUndoState()
assert [p.h for p in p.subtree()] == ['node 1', 'node 2', 'node 3']

# Select 'node 1' and modify the headline as if a user did it
node1 = p.copy().moveToFirstChild()
c.selectPosition(node1)
c.editHeadline()
w = c.frame.tree.edit_widget(node1)
w.insert('1.0', 'changed - ')
c.endEditing()
assert [p.h for p in p.subtree()] == ['changed - node 1', 'node 2', 'node 3']

# Move the selection and undo the headline change
c.selectPosition(node1.copy().moveToNext())
c.undoer.undo()

# The undo should restore the 'node 1' headline string
assert [p.h for p in p.subtree()] == ['node 1', 'node 2', 'node 3']

# The undo should put the edited headline into edit mode and not the node which was selected
g.es(node1); g.es(c.p)
assert c.p == node1, "The selected headline after undoing headline edit should be the edited headline"
</t>
<t tx="bpt.20190916110108.1"></t>
<t tx="bpt.20190916110117.1"></t>
<t tx="bpt.20190916110143.1"></t>
</tnodes>
</leo_file>
```

**Comment by edreamleo** [comment]
Done at d90fd69 in devel.  I won't say "fixed", because the old behavior was not clearly wrong.

The changes to undo and redo are trivial.  They can be restored if necessary.

**Comment by btheado** [comment]
Your change does not fix the failing unit test I included in the description.  I expect the headline to be restored to edit mode, just that I was hoping the "proper" headline would be put into edit mode. It sounds like you don't fully agree with me that there is a "proper" headline to put into edit mode...that putting any unrelated headline in edit mode is fine.

I'm not 100% sure, but I think your change is a net positive, so I'm not going to complain. Thanks for it. If I still find I want the behavior illustrated by my unit test, then I can look into contributing the change myself.

The behavior I'm asking for would be consistent with how body typing undo works. If I type in a body and then move the selection to some other node and then undo, the node in which the typing is undone becomes the selected node.

**Comment by btheado** [comment]
Works great, thanks for the fix!

**Comment by edreamleo** [comment]
@btheado Glad to hear it.
