### ISSUE TITLE
Console gui doesn't ask to create leoid

### ISSUE THREAD

**Issue by maphew** [leo-editor/leo-editor#1385]
**Recipe:**
~~~
set HOME=%temp%\%random%
leo-console
REM Or:
REM python launchLeo.py --gui=console
~~~

Result (loads and then quits without warning or error):
~~~
(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
> leo-console

--global-docks: False

loading npyscreen

(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
>
~~~

**Comment by edreamleo** [comment]
Fixed at b248ee4.

**Comment by maphew** [comment]
Confirmed working here. Since it uses a Tkinter dialog I don't think it would though over, say, an ssh console session. Workaround:

    pushd %HOME%
    mkdir .leo
    echo "my-user-id" > .leo\.leoID.txt

    leo-console

**Comment by maphew** [comment]
I take it back NOT fixed, or more accurately: bug #1373 is not fixed and it's revealed here. Dir `.leo` is created under current working directory and not under HOME.

~~~
(leo-dev) matt@ENV-SURFACE-MHW C:\Users\mattw\code\leo-editor
> set home=%temp%\%random%

> echo %home%
C:\Users\mattw\AppData\Local\Temp\2136
> leo-console

created directory: C:/Users/mattw/code/leo-editor/.leo
--global-docks: False

leoID='test'
.leoID.txt created in C:/Users/mattw/code/leo-editor/.leo
loading npyscreen
Leo 6.1-devel, devel branch, build b248ee45ab
2019-10-13 15:23:35 -0500
wrote C:/Users/mattw/code/leo-editor/.leo/leo.session
~~~

I'm leaving this one closed and re-opening 1373.
