### ISSUE TITLE
toggle-angle-brackets doesn't flag file as changed

### ISSUE THREAD

**Issue by largo84** [leo-editor/leo-editor#1449]
1. Use a 'clean' file (saved, no other changes).
2. Select any node.
3. invoke the command `toggle-angle-brackets` and let it change the headline to have (or not have) angle brackets.
4. Note the file is not marked changed (dirty?) If you do nothing else, but close the file and reopen it, the change is not preserved.

Environment:
`Leo 6.2-b1-devel, devel branch, build 17a59d4ad2`
`2019-11-16 06:21:47 -0600`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.18362) SP0`

**Comment by edreamleo** [comment]
Fixed at 701b4b9 in devel.

**Comment by largo84** [comment]
Hmm, not sure why this still doesn't work for me. I toggled several headlines to angle brackets and made no other changes. The file is not marked `dirty` to save changes. FWIW, these nodes were not in `@file` or `@clean` trees (not that it should matter, I think).

`Leo 6.2-b1-devel, devel branch, build 4c34367675`
`2019-12-18 05:56:24 -0600`
`Python 3.7.3, PyQt version 5.9.6`
`Windows 10 AMD64 (build 10.0.18362) SP0`

**Comment by edreamleo** [comment]
On Wed, Dec 18, 2019 at 7:18 AM Rob Keeney <notifications@github.com> wrote:

> I toggled several headlines to angle brackets and made no other changes.
> The file is not marked dirty to save changes.
>
Oops!  Rev 1667e84 in devel marks the outline as changed.

Edward

**Comment by largo84** [comment]
Confirmed it works as expected.
Rob...

**Comment by edreamleo** [comment]
@largo84 Thanks for the confirmation.
