### ISSUE TITLE
TypeError in spell.create

### ISSUE THREAD

**Issue by metaperl** [leo-editor/leo-editor#1453]
Not fixed via https://github.com/leo-editor/leo-editor/issues/713

I installed Leo from git this morning via `git clone --depth=500 https://github.com/leo-editor/leo-editor` and after running `python launchLeo.py` I got the following in the transcript window:

```
Leo Log Window
Leo 6.1-final, master branch, build b80e074204
2019-11-08 12:36:03 -0600
Python 3.8.0, PyQt version 5.13.0
Windows 10 AMD64 (build 10.0.17763) SP0
created directory: C:/Users/C050536/.leo
leoID='metaperl'
.leoID.txt created in C:/Users/C050536/.leo
current dir: C:/bin/leo-editor
load dir: C:/bin/leo-editor/leo/core
global config dir: C:/bin/leo-editor/leo/config
home dir: C:/Users/C050536
reading settings in C:/bin/leo-editor/leo/config/leoSettings.leo
Do spellpyx.txt file found
unexpected error creating: None
Traceback (most recent call last):

  File "C:\bin\leo-editor\leo\commands\spellCommands.py", line 56, in create
    f = open(fn, mode='wb')

TypeError: expected str, bytes or os.PathLike object, not NoneType

reading settings in C:/bin/leo-editor/leo/doc/CheatSheet.leo
```

**Comment by edreamleo** [comment]
Likely fixed at rev c12336 in the mkdirs branch.

**Comment by btheado** [comment]
c12336ccc8c does not fix this issue. It looks to me like this issue was introduced by 2d17e29a26b. Prior to that change, the find_user_dict method on a fresh installation would return $HOME/.leo/spellpyx.txt as the filename and that file would be created.

However, the code was changed to return `None` and so the file will never get created. A new leo user will always see this error whenever starting leo. The commit message for 2d17e29a26b is

> Last minute bug fix in the logic that finds the spelling dict.

But I didn't find any information on what bug that change was trying to fix.

**Comment by edreamleo** [comment]
Rev a08db7 in devel should fix this issue. Please reopen if not.

**Comment by btheado** [comment]
Confirmed the traceback related to spellpyx.txt is no longer displayed when running leo like a new user (i.e. no $HOME/.leo dir). Thanks.

**Comment by edreamleo** [comment]
@btheado You're welcome. Thanks for the confirmation.
