### ISSUE TITLE
It should be possible to generate Leo's Documentation locally

### ISSUE THREAD

**Issue by ranvik14** [leo-editor/leo-editor#1566]
I've tried for a while to re-create Leo's Documentation locally to have full access to it, even if I'm not online. - I've not succeeded so far - and - have documented my attempts here:

- https://groups.google.com/d/msg/leo-editor/lOBQ0fkWtpA/dh59eGDmAgAJ - and
- https://groups.google.com/d/msg/leo-editor/lOBQ0fkWtpA/fDWO7DRqBAAJ

**Comment by tbpassin** [comment]
I was able to build it on Windows, except that the top-level document (the toc.html) was completely wrong.  Otherwise, each individual section seems to be right.  I built it using a separate terminal, using the following command line:

```
py38 -m sphinx -C -D  master_doc=leo_toc.html -D source_suffix=.txt -D html_theme=sphinx_rtd_theme -D "project=Leo Docs"  . result
```
Note that I had previously set the current directory to be ``./html``, since that is where these ``.html.txt`` files are located by the ``rst3`` command.

The sphinx_rtd_theme directive can be omitted.  It changes the appearance but not the functionality.

I will take a look at the toc page and see what I can see.  At first glance, it looks very different from how I thought toc pages are supposed to look, but I'm no expert.

**Comment by tbpassin** [comment]
I have found one of the problems.  This may only be a problem when building from the command line in the most simple way.  Maybe the config file has some instruction for overcoming it.

All the .rst source files have the name pattern ``xxx.html.rst``. In the leo_toc.html.rst file, these files are referred to without the ``.html`` extension.  When I added the extension, then the TOC page built correctly.

For example::
```
  Users Guide <usersguide> -->Users Guide <usersguide.html>
  screencasts -> screencasts.html
```

**Comment by tbpassin** [comment]
I found the configuration item that makes the Sphinx build work without having to add ".html" in the toc entries::

    -D source_suffix=".html.txt"

You can add this to the command line options.  So the command line to build the docs becomes::

    py38 -m sphinx -C -D  master_doc="html/leo_toc" -D source_suffix=.html.txt -D html_theme="sphinx_rtd_theme" -D project="Leo Docs" . result

**Comment by edreamleo** [comment]
@tbpassin Good work, Tom.

**Comment by tbpassin** [comment]
To be complete about it, here is a script (for Windows, anyway) that successfully builds the docs for me.  I have this script in an ``@button`` node
```
import os
python = r'C:\Users\tom\AppData\Local\Programs\Python\Python38\python.exe'

cmd = rf"""{python} -m sphinx -C -D  master_doc="html/leo_toc" -D source_suffix=.html.txt -D html_theme="sphinx_rtd_theme" -D project="Leo Docs"  . result"""

os.system(f'cmd /c {cmd}')
```


You could also have the script invoke the ``rst3`` command first, but then you would have to select the topmost node in the docs first.  This is easy for me to forget.

**Comment by maphew** [comment]
This can be made OS neutral by by changing `python =` line:

    import sys
    pyexe = sys.executable

Personally I think `pyexe` as var name is more explicit than `python`, YMMV.

**Comment by tbpassin** [comment]
Oh, that's very nice.  I haven't used that idom before and I like it.  I don't think that invoking ``cmd /c`` is OS neutral, though.  I *think* that quoting the argument value is, isn't it?  The only argument that would need quoting is the one with the space in it: ``-D project="Leo Docs"``

**Comment by tbpassin** [comment]
If we are going for full OS neutrality, the following ought to do it -
```
import sys
import subprocess
pyexe = sys.executable
cmd = [pyexe, '-m', 'sphinx', '-C', 
          '-D' 'master_doc=html/leo_toc',
          '-D', 'source_suffix=.html.txt',
          '-D', 'html_theme=sphinx_rtd_theme',
          '-D', 'project=Leo Docs',
          '.', 'result']

subprocess.call(cmd)
```

It works on my machine.

**Comment by ranvik14** [comment]
I can confirm, that your approach is working on Fedora 30.

I did create a new button 'create-local-doc' with the content of your OS neutral version in outline 'LeoDocs.leo'.

When executing the button the first time, Sphinx reported an error related to the missing 'html_theme'.

After I installed the missing dependency 'sphinx_rtd_theme' using pip - and - tried the button 'create-local-doc' again, it did create Leo's documentation locally in my VM at location

- file:///home/user/PyVE/PyPI/Leo-stable/lib/python3.7/site-packages/leo/doc/result/html/leo_toc.html

All screenshots & slides are missing, but otherwise all/ most of the content seems to be available.

**Comment by tbpassin** [comment]
I'm glad it worked for you, too, and cross-platform at that.  I didn't get the images and slides, either.  I had copied the outline to a new one somewhere else, so I could experiment without risk of cluttering up or corrupting my Leo code tree.  I assumed that the images were in the original location, but I didn't actually look for them there.

If they aren't included with the distribution package, I would suggest that they be added for future builds, just for the purpose of building the docs oneself.

Also, the sphinx-rtd theme isn't really needed. That ``-D`` parameter could be removed from the ``cmd`` list.  The output would still be created, just not with the Read-The-Docs appearance.

**Comment by maphew** [comment]
So it looks like the initial spark for this issue has been resolved, local building of Leo docs is working. Does anyone want to take a crack at writing a short and sweet recipe for the docs?

**Comment by tbpassin** [comment]
I don't think we're quite there yet.  I see several hitches.

1.  The image links don't work.  I haven't sorted my way through this yet.  The images seem to be in the distribution, but not in the right place to get picked up by the build script.  There seem to be two groups of images, one for screen shots and one for slides.  I know where the screenshots are, though they don't get linked correctly.  I don't yet know where the others are.

2. Each and every @file file in the leoDocs outline is in the html directory.  There ought to be a single @path node at the top, and then all the @files would just have their names, and not be prefixed by ``html/``.  This requires a small change to the build script, and presumably to the Sphinx conf.py file as well for the traditional way of building.

3. There are several @auto-md nodes.  I don't know how these are supposed to build, since everything else is @rst.

**Comment by tbpassin** [comment]
> I don't think we're quite there yet. I see several hitches.
> 
>     1. The image links don't work.  I haven't sorted my way through this yet.  The images seem to be in the distribution, but not in the right place to get picked up by the build script.  There seem to be two groups of images, one for screen shots and one for slides.  I know where the screenshots are, though they don't get linked correctly.  I don't yet know where the others are.

In my latest run, the screen shot images get relocated and linked as they should.  I'm still not sure about how the slides should be handled.

**Comment by edreamleo** [comment]
I am going to mark this issue as delegated.  This helps me keep track of issues that I need to do.

**Comment by ranvik14** [comment]
@edreamleo : I've started my work on this issue. - Currently I see the following tasks:

1. Create a button 'create local docs'.
2. Add 'sphinx_rtd_theme'  as a dependency for Leo.
3. Create a button 'view local docs'.

Tasks 1 & 2 are easy / were already done.

However the results, when applied to the current version of the "leoDocs.leo" outline, are not satisfactory. - See below:

```
    (Leo) [user@fedora-leo-study-vm Leo]$ 
    (Leo) [user@fedora-leo-study-vm Leo]$ Running Sphinx v3.5.3
    building [mo]: targets for 0 po files that are out of date
    building [html]: targets for 50 source files that are out of date
    updating environment: [new config] 50 added, 0 changed, 0 removed
    reading sources... [100%] html\writingPlugins                                   
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/intermediatetopics.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/coloring'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/intermediatetopics.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/writingPlugins'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/intermediatetopics.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/unitTesting'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/intermediatetopics.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/debuggers'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/intermediatetopics.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/console-gui'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/intermediatetopics.html.txt:17: WARNING: toctree contains reference to nonexisting document 'html/scripting-miscellany'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/intermediatetopics.html.txt:17: WARNING: toctree contains reference to nonexisting document 'html/leonine-world'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/intermediatetopics.html.txt:17: WARNING: toctree contains reference to nonexisting document 'html/leo-university'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/leo_toc.html.txt:24: WARNING: toctree contains reference to nonexisting document 'html/cheatsheet'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/leo_toc.html.txt:29: WARNING: toctree contains reference to nonexisting document 'html/tutorial'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/leo_toc.html.txt:39: WARNING: toctree contains reference to nonexisting document 'html/FAQ'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/leoandotherprograms.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/emacs'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/leoandotherprograms.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/vimBindings'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/leoandotherprograms.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/leoBridge'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html/leoandotherprograms.html.txt:7: WARNING: toctree contains reference to nonexisting document 'html/IPythonBridge'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\console-gui.html.txt:7: WARNING: image file not readable: screen-shots/console-window.png
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\console-gui.html.txt:7: WARNING: image file not readable: screen-shots/console-window.png
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:14: WARNING: toctree contains reference to nonexisting document 'preliminaries'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:19: WARNING: toctree contains reference to nonexisting document 'getting-started'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:24: WARNING: toctree contains reference to nonexisting document 'cheatsheet'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:29: WARNING: toctree contains reference to nonexisting document 'screencasts'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:29: WARNING: toctree contains reference to nonexisting document 'tutorial'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:29: WARNING: toctree contains reference to nonexisting document 'usersguide'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:29: WARNING: toctree contains reference to nonexisting document 'leoandotherprograms'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:29: WARNING: toctree contains reference to nonexisting document 'intermediatetopics'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:29: WARNING: toctree contains reference to nonexisting document 'appendices'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:39: WARNING: toctree contains reference to nonexisting document 'history'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:39: WARNING: toctree contains reference to nonexisting document 'FAQ'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:39: WARNING: toctree contains reference to nonexisting document 'glossary'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:39: WARNING: toctree contains reference to nonexisting document 'what-is-new'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:47: WARNING: toctree contains reference to nonexisting document 'slides'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:47: WARNING: toctree contains reference to nonexisting document 'leoLinks'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt:47: WARNING: toctree contains reference to nonexisting document 'screen-shots'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial.html.txt:26: WARNING: toctree contains reference to nonexisting document 'tutorial-basics'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial.html.txt:26: WARNING: toctree contains reference to nonexisting document 'tutorial-pim'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial.html.txt:26: WARNING: toctree contains reference to nonexisting document 'tutorial-rst3'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial.html.txt:35: WARNING: toctree contains reference to nonexisting document 'tutorial-scripting'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial.html.txt:42: WARNING: toctree contains reference to nonexisting document 'tutorial-tips'
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial-basics.html.txt:: WARNING: image file not readable: screen-shots/leo-workbook.png
    looking for now-outdated files... none found
    pickling environment... done
    checking consistency... /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\FAQ.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\IPythonBridge.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\cheatsheet.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\coloring.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\console-gui.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\debuggers.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\emacs.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo-university.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leoBridge.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leo_toc.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\leonine-world.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\scripting-miscellany.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial-basics.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial-pim.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial-rst3.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial-scripting.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\tutorial-tips.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\vimBindings.html.txt: WARNING: document isn't included in any toctree
    /home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/html\writingPlugins.html.txt: WARNING: document isn't included in any toctree
    done
    preparing documents... done
    writing output... [100%] html\writingPlugins                                    
    generating indices... genindex done
    writing additional pages... search done
    copying images... [100%] html/screen-shots/leo-thesis.png                       
    copying static files... done
    copying extra files... done
    dumping search index in English (code: en)... done
    dumping object inventory... done
    build succeeded, 59 warnings.

    The HTML pages are in result.

```
It is not clear (at least to me), what is considered part of Leo's documentation, what is part of Leo's home- / project page - and - what is simply still 'historically' part of the "LeoDocs.leo" outline?

Any recommendations & suggestions on how to proceed?

**Comment by ranvik14** [comment]
@edreamleo : Here's the current 'flow', when creating the documentation via the 'create local doc' button:

* Leo’s Documentation Page
* file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/leo_toc.html
* -> Preliminaries
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/preliminaries.html
* -> Downloading, Installing & Running Leo
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/getting-started.html
* -> Videos about Leo
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/screencasts.html
* -> Leo’s Users Guide
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/usersguide.html
* -> Leo and Other Programs
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/leoandotherprograms.html
* -> Advanced Topics
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/intermediatetopics.html
* -> Appendices
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/appendices.html
* -> History of Leo
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/history.html
* -> Glossary
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/glossary.html
* -> What’s New in Leo
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/what-is-new.html
* -> Slides
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/slides.html
* -> More Leo Resources
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/leoLinks.html
* -> Leo screen shots
* -> file:///home/user/PyVE/GitHub/Leo/leo-editor/leo/doc/result/html/screen-shots.html

**Comment by tbpassin** [comment]
I just tried this myself for the node with headline "Leo's Documentation".  I used the script I posted above on Apr 7, 2020.  I only got one warning:

```
 WARNING: toctree contains reference to nonexisting document 'html/unitTesting'
```

I haven't examined the output closely yet but superficially it looks all right.

**Comment by ranvik14** [comment]
@tbpassin : I've checked in my setup again, and - the 59 warnings shown before - stay.

What I did not state explicitly, is that this setup is a Fedora Linux 34 VM - but - my assumption was, that this should not matter.

The output does look OK. - One thing that I noticed, is that the 'slide' content is not accessible ...

However I (personally) do not consider the 'slides' part of Leo's User Documentation, but part of Leo's Home-/ Project Page.

This is why I asked Edward for advice.

**Comment by ranvik14** [comment]
@edreamleo & @tbpassin : I'm always explicitely mentioning Leo's user docu vs. Leo's home-/ project page - because - I see another open issue: **Host Leo's web site on GitHub**

- https://github.com/leo-editor/leo-editor/issues/480

where the interaction b/w the two issues is unclear to me ...

**Comment by edreamleo** [comment]
@ranvik14 My quick summary:

- Leo's home page is a special case. For now, you shouldn't need to worry about it.
- For now concentrate on creating all files (pages) from the top-level node "Leo's Documentation" in LeoDocs.leo.

**Comment by ranvik14** [comment]
> I just tried this myself for the node with headline "Leo's Documentation". I used the script I posted above on Apr 7, 2020. I only got one warning:
> 
> ```
>  WARNING: toctree contains reference to nonexisting document 'html/unitTesting'
> ```
> 
> I haven't examined the output closely yet but superficially it looks all right.

@tbpassin : Can you please let me know if your locally created documentation matches the 'official' documentation available at  https://leoeditor.com/leo_toc.html ?

In my case it does not ...

For example the sections on "Cheat Sheet" and "Tutorials" are completely missing !

**Comment by ranvik14** [comment]
@tbpassin : Now I'm really puzzled. - I tried it now also in a Debian 11 VM - and - had identical results to the ones I documented for Fedora 34. - I need to do some more 'investigations' on my side ...

**Comment by ranvik14** [comment]
@tbpassin : Now I know a little bit more.

The generation of Leo's documentation locally works only on Windows (at least for me)!

Can you confirm, that you made your previous statement on the local documentation from a Windows-based installation?

**Comment by tbpassin** [comment]
Yes, that is so.  I will check this, but I seem to recall that if I run rst3 first I get a different result.  And I *think* (to be checked) that the same was true on a Linux VM.

**Comment by tbpassin** [comment]
I have found the source of most of the problems and of the different results between building on Linux vs Windows.  In the _Leo's Documentation_ tree, there are a number of files whose headlines start with 

```@rst html\```

These should, of course, start with

```@rst html/```

These need to be fixed.  Then, especially in linux, go into the build directory (_html_ for Leo's build scripts or _result/html_ for my script)  and delete all files whose names start with *html\\*.

Now run the _rst3_ command and the docs should build correctly.

**Comment by ranvik14** [comment]
@tbpassin : Using your advice plus one more small adjustment, I'm now able to create Leo's documentation locally inside a Fedora 43 VM **without** any warning ...

This is a big step forward, thanks to your analysis !

I plan to create a PR for it during the next weekend. - I need to do some reading & experiments on my side, to ensure that it will be usable for @edreamleo  ;-)

**Comment by edreamleo** [comment]
@ranvik14 Well done. Thanks for your work.
