### ISSUE TITLE
Unexpected behavior when binding ! tree = PageUp

### ISSUE THREAD

**Issue by JohnLunzer** [leo-editor/leo-editor#416]
I've set these key shortcuts:
```
goto-next-n-visible   ! tree = PageDn
goto-prev-n-visible   ! tree = PageUp
```
Here is my @command goto-next-n-visible node:
```python
@language python
N=12

def getVisNextN(n):
    current = c.p
    for ind in range(n):
        forward = current.getVisNext(c)
        if forward != None:
            current = forward
        else: break
    return current
    
NAhead = getVisNextN(N)

c.setCurrentPosition(NAhead)
c.redraw()
```
I think it's fairly straight forward, instead of the current behavior which just scrolls, this actually moves you down N number of nodes. This behavior makes more sense to me, but despite that feeling I don't have enough evidence to believe it should be default.

Anyway, this particular key shortcut does not work. Instead it pastes "PageDn" or "PageUp" in the body and places the cursor between the "P" and the "a".

Weird. As a point of comparison I can confirm that the commands themselves work as expected as I previously had these commands bound to:
```
goto-next-n-visible         = Alt+UpArrow
goto-prev-n-visible         = Alt+DnArrow
```
And the behavior is as expected. 

Here is my version number:
```
Leo 5.4, build 20170221043749, Tue Feb 21 04:37:49 CST 2017
Git repo info: branch = master, commit = f860468937d5
Python 2.7.13, PyQt version 4.8.6
Windows 7 AMD64 (build 6.1.7601) SP1
```

**Comment by JohnLunzer** [comment]
I have some more information. 

The binding:
```
toggle-invisibles ! tree = PageDn
```
does toggle the invisibles when in the tree without pasting anything in the body, but has the same effect of pasting "PageDn" in the body when I press the page down button when the body editor is active. 

Basically just confirming that the behavior appears the same when using builtin commands as well as custom commands.

**Comment by edreamleo** [comment]
Fixed at e3910ae. Please reopen if there are further problems.

**Comment by JohnLunzer** [comment]
Updating to e3910ae did not fix my problem.

When I'm in myLeoSettings.leo the keybinding works correctly in the tree but exhibits the same erroneous behavior in the text body. I should clarify further. I can have multiple .leo tabs open but only when the myLeoSettings.leo tab is active will does the originally stated keybinding work in the tree.

To that end, printing keybindings in myLeoSettings.leo shows my custom keybindings while printing the keybindings in other .leo files does not.

Additionally I have a couple other keybindings that only work in myLeoSettings.leo:
```
mark-and-goto-next ! tree    = Space
quick-replace                         = Ctrl-/
```
All of these bindings have something in common, they're all custom @command nodes in my @settings node of myLeoSettings.leo

These commands are indeed getting registered in all commanders/.leo files because I can use the minibuffer to execute them anywhere.

An exception to what I stated above is that this most recent update made my `! tree = Space` shortcut stop working in myLeoSettings.leo as well.

Please let me know if you need more information.

**Comment by edreamleo** [comment]
> All of these bindings have something in common, they're all custom @command nodes in my @settings node of myLeoSettings.leo

To make *global* `command` nodes, you must put them in an `@commands` node:

```
- @settings
    - @commands
          - @command my-command-1
          - @command my-command-2
```
This is explained at `leoSettings.leo#@settings-->Common @command nodes-->@commands` as follows:

```
All @command nodes in the @commands tree define **global commands** that appear in all Leo outlines.

All other @command nodes define **local commands** that are defined only in this outline.
```

**Comment by JohnLunzer** [comment]
They are being defined globally.  Additionally it's not just my custom commands that are still the problem, my issue wasn't resolved via the update.

**Comment by JohnLunzer** [comment]
To be clear, I know they are being defined globally because I can run them in the minibuffer from all commanders.

**Comment by edreamleo** [comment]
Ok.  From your description it looks like there is a problem with `@key` bindings in common `@command` nodes.  Likely the same problem exists in common `@button` nodes.

**Comment by edreamleo** [comment]
In general, common `@command` and `@button` nodes work as expected.

As you say, PageUp/Dn (Prior, Next) seem to be hard coded in the tree. So this is a binding problem, not anything to do with the mod_scripting plugin.

**buglet**: `print-bindings` reports: `D <the binding> @command-key-test`

It should be `M` for a stroke defined in myLeoSettings.leo, not `D`, for a default keystroke.

**Comment by edreamleo** [comment]
Rev b732cf9 fixes this.
