### ISSUE TITLE
Searching on LeoEditor site is broken

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#789]
From [this post](https://groups.google.com/forum/#!msg/leo-editor/9QVGUdknD6k/unsN6kKsBAAJ). Missing pages on leo-editor: Links have an additional '.txt.hml' added to the URL:

Wrong: http://leoeditor.com/cheatsheet.html.txt.html?highlight=paste
Correct: http://leoeditor.com/cheatsheet.html?highlight=paste

**Update**: All appears to work after hacking searchindex.js, but this is only a temporary solution.  See below.  I have asked for help with [this post](https://groups.google.com/d/msg/sphinx-users/yZUO7M65B04/2rhFMsfZAwAJ) on the [sphinx-users group](https://groups.google.com/forum/#!forum/sphinx-users). No reply yet.

**Comment by edreamleo** [comment]
Fixed at b28737a. Leo's home page now uses google search, which seems good enough.

**Comment by largo84** [comment]
Still not working. Try searching for 'language' and the site is searching the old HostGator site.
![image](https://user-images.githubusercontent.com/9388145/37574481-796b3188-2af7-11e8-8d78-c92048129713.png)

**Comment by tbnorth** [comment]
On Mon, 19 Mar 2018 01:58:29 +0000 (UTC)
Rob Keeney <notifications@github.com> wrote:

> Still not working. Try searching for 'language' and the site is
> searching the old HostGator
> site. ![image](https://user-images.githubusercontent.com/9388145/37574481-796b3188-2af7-11e8-8d78-c92048129713.png)

Looks like the broken search is not replaced everywhere.  It's fixed on
http://leoeditor.com/
but still the old one on
http://leoeditor.com/leo_toc.html

**Comment by largo84** [comment]
But even on http://leoeditor.com/ if you go deeper, then use Quick search, you get the failed 404s.

**Comment by edreamleo** [comment]
On Sun, Mar 18, 2018 at 10:11 PM, Rob Keeney <notifications@github.com>
wrote:

> But even on http://leoeditor.com/ if you go deeper, then use Quick
> search, you get the failed 404s.
>
​Thanks for this report.  I'll fix this soon.

Edward

**Comment by edreamleo** [comment]
The proximate cause of this issue is that searchindex.js contained a "filenames" array whose elements had .html.txt extensions.  I changed searchindex.js so that the "docnames" and "filename" arrays are identical.

All appears to work properly after uploading the new searchindex.js to Leo's web site. Naturally, this is an unsatisfactory "solution", but searching will continue to work as long as searchindex.js stays as it is.

Presumably, the .html.txt extension comes from the leo/docs/html/conf.py. This tells sphinx file type of the input files.  Why this should affect the quick search box is a mystery. The sphinx docs to not seem helpful.  It's probably time to ask the sphinx group for help.

**Comment by edreamleo** [comment]
The PR fixed this problem in an elegant way.
